[Http-Requests 2018-09-12 17:02:38,574 HTTP_requests.py HTTP_requests  INFO] ===》 获取接口地址成功：ht[damao 2018-09-12 17:02:39,256 test_my_demo.py test_my_demo  INFO] ===》 请求体参数：params:{'c': 1}
[damao 2018-09-12 17[Http-Requests 2018-09-12 17:02:39,259 HTTP_requests.py HTTP_requests  INFO] ===》 获取接口地址成功：http://httpbin.org/
[Http-Requests 2018-09-12 17:02:40,034 HTTP_requests.py HTTP_requests  INFO] ===》 get请求发送成功！
ate', 'Accept': '*/*', 'Connection': 'keep-alive'}
[damao 2018-09-1[python 2018-09-12 17:02:41,448 run.py run  INFO] ===》 邮件发送成功！
[python 2018-09-12 17:02:41,449 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-08-18-02-12-47.log' already exists
[python 2018-09-12 17:02:41,449 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-08-18-02-14-21.log' already exists
[python 2018-09-12 17:02:41,450 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-08-18-02-19-01.log' already exists
[python 2018-09-12 17:02:41,450 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-08-18-02-19-02.log' already exists
[python 2018-09-12 17:02:41,451 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-08-24-15-47-16.log' already exists
[python 2018-09-12 17:02:41,451 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-08-31-18-23-18.log' already exists
[python 2018-09-12 17:02:41,451 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-08-31-18-23-19.log' already exists
[python 2018-09-12 17:02:41,452 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-09-01-11-21-36.log' already exists
[python 2018-09-12 17:02:41,452 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-09-10-09-34-49.log' already exists
[python 2018-09-12 17:02:41,453 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-09-12-10-17-45.log' already exists
[python 2018-09-12 17:02:41,453 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-09-12-11-30-43.log' already exists
[python 2018-09-12 17:02:41,457 run.py run  INFO] ===》 剪切失败：[WinError 32] 另一个程序正在使用此文件，进程无法访问。: '.\\logs\\log_file\\auto_test_2018-09-12-17-02-38.log'
